# Generated by Django 3.0.8 on 2020-08-07 18:07

from django.db import migrations
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20200804_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='my_figure',
            field=django_matplotlib.fields.MatplotlibFigureField(),
        ),
    ]
